document.addEventListener("DOMContentLoaded", function () {
  const topics = {
    "Professional Questions": [
      "How did you get your start in this career field?",
      "What has been one of your favorite or most memorable projects so far?",
      "What significant skills have you gained from your past roles?",
      "What appealed to you about this position and led you to join the team?",
      "What's your go-to strategy for staying productive during the workday?",
      "How do you typically manage your time and prioritize tasks?",
      "Have you overcome any big work challenges? What did you learn?",
      "What is your favorite part of your job?",
      "What work achievements make you feel most proud and fulfilled?",
      "What are your strengths at work? And areas you want to grow?",
      "What skills training or growth opportunities interest you right now?",
      "What gives you energy and motivation at work?",
      "What tends to drain your energy at work?",
      "What work skills do you hope to develop in the future?",
      "Who or what inspires you to do your best?",
      "What professional skills do you think everyone should have?",
      "What accomplishments are you most proud of so far?",
      "How do you prefer receiving constructive feedback?",
      "How do you like collaborating with colleagues and teammates?",
      "Tell us more about your ideal work environment.",
      "Is there a particular role you'd like to work toward in the future?",
      "If you could have any career, what would it be?",
      "What are your long-term career goals? Where do you see yourself in 5 years?",
    ],
    "Interests & Hobbies": [
      "What would it be if you could speak any language?",
      "What hobbies help you unwind after work hours?",
      "What's a new skill you'd love to learn or activity you want to try?",
      "What's on your bucket list before your 30s? Have you already checked off any items?",
      "What topic could you talk enthusiastically about for hours?",
      "What topic could you give a 30-minute presentation on without prep?",
      "What's your favorite home-cooked meal or takeout order?",
      "How do you stay active when working from home?",
      "What's your ideal way to spend a day off when you can't go out much?",
      "If you could see any concert, who would you want to see live?",
      "What podcasts or YouTube channels can you listen to for hours?",
      "Do you have any guilty habits?",
      "What hobby or activity do you wish you had more time for?",
      "Are you a collector of anything?",
      "Do you have any artistic or creative talents?",
      "Do you play any musical instruments?",
      "What sports or e-sports are you into?",
      "What YouTube channels or social media accounts do you geek out over?",
      "What's something you've always wanted to try but haven't yet - like learning a language or coding?",
      "What have you hyper-fixated on learning about recently?",
    ],
    "Personality & Values": [
      "Tell us about your top 3 values in life.",
      "What causes are you passionate about?",
      "Share a motto, quote, or mantra that inspires you.",
      "Who are your biggest inspirations lately, and why?",
      "What personal accomplishments are you proud of?",
      "How would your close friends describe you?",
      "What makes you truly happy during this time?",
      "What are some things you're feeling grateful for right now?",
      "What are some of your best and worst personality traits?",
      "How do you react to stress and changes at work and in life?",
      "What makes you feel fulfilled?",
      "What quality do you admire most in others?",
      "What personal challenges have shaped who you are?",
      "What worries or fears have come up for you during this time? And how do you manage them?",
      "How do you want to impact others positively?",
      "What stereotype about yourself is actually true?",
      "What are you still trying to figure out about yourself?",
      "What personal goals are you working toward or have pivoted to focus on now?",
    ],
    Favorites: [
      "What's your go-to morning beverage?",
      "What is your favorite book/TV show/movie/song?",
      "What fictional world or series would you want to live in?",
      "Which celebrity would you want to be best friends with?",
      "What apps or websites could you browse for hours?",
      "What video game have you played the most, or are you interested in watching people playing?",
      "What movie title best describes your life?",
      "What trend or period in history most inspires your style?",
      "What fashion accessories do you wear every day?",
      "What adventure have you been dying to go on?",
      "What pop culture moments really defined your childhood?",
      "What food could you eat daily and not get tired of?",
      "What songs take you right back to your teenage years?",
      "What candy or soda do you have fond memories of?",
      "What fictional character do you relate to most?",
      "What book has had the biggest impact on you?",
      "What actor or musician would you most want to meet?",
      "What theme park ride are you obsessed with?",
      "What city best aligns with your personality?",
      "What cuisine are you a die-hard fan of?",
    ],
    "Dreams & Goals": [
      "Where would your dream home be if you could live and work from anywhere?",
      "What is the best vacation you’ve ever taken?",
      "What is your dream travel destination?",
      "What hobby would you get into if time and money weren’t an issue?",
      "What would you do if you won the lottery?",
      "What did you want to be when you grew up?",
      "What would you change about the city you live in if you could?",
      "What career or business idea have you always wanted to try?",
      "What fictional job would you want to have?",
      "What goals are you focused on this year?",
      "What achievements will you feel proudest of at the end of your life?",
      "What would the title be if you wrote a book about your life?",
      "What do you want your epitaph to say?",
    ],
    "Personal Work-Life Balance": [
      "Describe your ideal workday.",
      "Would you consider yourself a workaholic? And do people say so about you?",
      "What does 'work-life balance' mean to you?",
      "How do you like to unwind and recharge after a long work week?",
      "What habits help you maintain energy?",
      "What do you do to enter a focused mode, and what will break it?",
      "Are you an introvert or an extrovert? How does that impact your need for downtime?",
      "How do you set boundaries with work to protect personal time?",
      "Do you struggle to unplug from work? If so, what do you think the reasons are?",
      "What are your number one tips for avoiding burnout?",
      "What's your favorite music to play when you need a mood boost?",
      "When do you truly feel you’ve 'clocked out' for the day?",
      "What always helps turn a bad day around for you?",
      "How do you stay motivated when work feels overwhelming?",
      "Where do you go, or what do you do when you need inspiration?",
      "Do you have any rituals before and after long meetings?",
      "What are some warning signs that your work-life balance is off?",
      "What would your perfect Sunday look like?",
    ],
    "Unlock Team Dynamics": [
      "How would you describe yourself?",
      "What work environment do you thrive in?",
      "Do you prefer working alone or on a team?",
      "What qualities do you appreciate most in teammates?",
      "How do you handle disagreements and conflict? Does it change during remote work?",
      "How do you react to stressful situations?",
      "What could the team do to support you better?",
      "What are your pet peeves when collaborating?",
      "How do you like to be recognized or rewarded for great work?",
      "How do you prefer to receive feedback?",
      "What makes you feel valued on a team?",
      "What makes you trust and feel trusted at work?",
      "How do you think your colleagues would describe you?",
      "What are three fun facts about you that we may not know?",
      "If you could have a superpower, what would it be and why?",
      "What's your favorite team tradition or ritual?",
    ],
    "All About Remote Work": [
      "What do you like most about remote work?",
      "What do you miss most about working in the office?",
      "What's your favorite thing about your home office/workspace?",
      "What's your biggest pet peeve when it comes to virtual meetings?",
      "What's your favorite remote work tool or app?",
      'What\'s the most "interesting" thing that has happened in the background during a video call?',
      "What's your top tip for staying focused while working from home?",
      "What's the most important thing you've learned about remote work?",
      "What's your #1 remote work hack?",
      "What's your favorite background or virtual background to use on video calls?",
      "What advice would you give someone new to remote work?",
      "What's been the biggest adjustment working remotely?",
      'What\'s your typical "work from home" outfit?',
      "What's the most frustrating technical issue you've run into?",
      "What's your strangest WFH habit?",
      "What is your #1 productivity killer working remotely?",
      "What self-care practice is crucial on your busy work-from-home days?",
      "How has working remotely changed your daily routine?",
      "What's the best perk you've discovered working remotely?",
      'How do you separate "work" and "home" spaces when working remotely?',
      "What's the most surprising challenge about remote work? Is it still a problem for you?",
    ],
    "Would You Rather Questions": [
      "Email or Instant Messaging?",
      "Video Calls or Audio Calls?",
      "Morning Person or Night Owl?",
      "Home Office or Coffee Shop?",
      "Work in Silence or with Background Music?",
      "Scheduled Breaks or Frequent Short Breaks?",
      "Laptop or Desktop for Work?",
      "Strict Routine or Flexible Schedule?",
      "Virtual Backgrounds or Real Backgrounds?",
      "Coffee or Milktea?",
      "Paper Notebooks or Digital Notes?",
      "Introvert or Extrovert?",
      "One Task at a Time or Multitasking?",
      "Pomodoro Technique or Flow State?",
      "Home-Cooked Lunch or Takeout?",
      "News Check Twice a Day or Throughout the Day?",
      "Music or Podcast?",
      "Public Praise or Personal Act of Recognition?",
      "Document Everything or Rely on Memory?",
      "Data-Driven Decisions or Gut Feelings?",
      "Visual Learner or Auditory Learner?",
      "Morning Brainstorms or Afternoon Creativity?",
      "Face-to-Face Training or Online Courses?",
      "Inbox Zero or Inbox Infinity",
      "Risk-Taker or Cautious Planner?",
      "Millions of Tabs Open or Working Tabs Only?",
    ],
    "Cultural-fit Check": [
      "What would you be and why if you were an ice cream flavor?",
      "What drives you in your day-to-day work?",
      "What song would you sing on karaoke night?",
      "What's the most useless talent or skill you have?",
      "What would it be if you had to wear one outfit for the rest of your life?",
      "What's the silliest thing you're afraid of?",
      "What hobby would you get into if time and money weren't an issue?",
      "What's your favorite bad joke?",
      "What do you appreciate most about working in a team?",
      "What would it be if you could add one element to our company’s value?",
      "If you could add anyone from history to Mount Rushmore, who would it be?",
      "You’ve been given an elephant. You can’t give it away or sell it. What would you do with the elephant?",
      "What's the most childish thing you still do as an adult?",
      "When was the last time you messed up on a project or task?",
      "If you had a time machine, what period would you visit first?",
    ],
    "Freaky Fun Questions": [
      "What's the dumbest thing you've ever argued about with someone?",
      "What would it be if you could replace one body part with something weird?",
      "What's the weirdest dream you've ever had?",
      "What food do you think should be illegal?",
      "What mythical creature would you want as a pet?",
      "What's your favorite planet in the solar system, and why?",
      "If you could be any animal for a day, what would you be and why?",
      "What's the strangest thing you've witnessed someone do in public?",
      "What talent would you pick if you could instantly become an expert in something?",
      "What's the weirdest food combination you really enjoy?",
      "What mythical creature do you wish actually existed?",
      "If you could make up a new holiday, what would it be called, and how would people celebrate it?",
      "What are your crazy ideas for a reality show if you can make one?",
      "What's the strangest dream you've ever had?",
      "What is the silliest way you’ve injured yourself?",
      "What is the weirdest nickname you’ve ever had?",
      "What's the most useless app you have on your phone?",
      "What's the dumbest thing you've done that actually turned out pretty well?",
      "What's the most ridiculous thing you've done to impress someone?",
      "If you could live in any fictional world, which would you choose?",
    ],
    "Manager-Employee Deep Questions": [
      "How can I provide you with useful feedback and guidance?",
      "What are your professional growth goals this year? How can I help?",
      "What are your strengths that I should be sure to utilize?",
      "How would you describe your ideal management style?",
      "What makes you feel most motivated and empowered at work?",
      "What could I do to support you in your role better?",
      "How can we communicate most effectively together?",
      "How do you prefer to receive recognition or praise?",
      "What are your ideas for improving team collaboration and innovation?",
      "What kind of challenge do you want to try once?",
      "What excites you most day-to-day about the work you do?",
      "What types of professional development opportunities interest you?",
      "How can I help remove any obstacles standing in your way?",
      "How do you envision us working together most productively?",
      "What does your dream working environment look like?",
      "What are your priorities that I should keep in mind?",
      "How can I set you up for ongoing success in your role?",
    ],
  };

  const topicSelector = document.getElementById("topicSelector");
  const questionDisplay = document.getElementById("questionDisplay");
  const description = document.getElementById("description");

  // Populate topic selector
  for (let topic in topics) {
    let option = document.createElement("option");
    option.value = topic;
    option.textContent = topic;
    topicSelector.appendChild(option);
  }

  // Event listener for button
  document
    .getElementById("generateQuestion")
    .addEventListener("click", function () {
      let selectedTopic = topicSelector.value;
      let questions = topics[selectedTopic];
      description.style.display= "none";
      let randomQuestion =
        questions[Math.floor(Math.random() * questions.length)];
      questionDisplay.textContent = randomQuestion;
      this.textContent = "Next";
    });
});
